# Generated by Django 3.2.9 on 2022-01-05 19:22

import clothes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunny', models.BooleanField(default=False)),
                ('cloudy', models.BooleanField(default=False)),
                ('rainy', models.BooleanField(default=False)),
                ('snowy', models.BooleanField(default=False)),
                ('windy', models.BooleanField(default=False)),
                ('temperature', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'weather_type',
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('windy', 'Windy')], max_length=35)),
                ('cathegory', models.CharField(choices=[('none', 'None'), ('t-shirt', 'T-Shirt'), ('trousers', 'Trousers'), ('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('shorts', 'Shorts'), ('shirt', 'Shirt')], default='none', max_length=20)),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='clothes/default.jpg', upload_to=clothes.models.user_directory_path)),
                ('preference_index', models.IntegerField(default=1)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clothes_garment',
            },
        ),
    ]
