# Generated by Django 2.2.25 on 2022-01-09 15:57

import clothes.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('windy', 'Windy')], max_length=35)),
                ('cathegory', models.CharField(choices=[('none', 'None'), ('hat', 'Hat'), ('cover1', 'Outer layer'), ('cover2', 'Mid layer'), ('tshirt', 'T-Shirt'), ('trousers', 'Trousers'), ('boots', 'Boots')], default='none', max_length=20)),
                ('name', models.CharField(default='', max_length=200, verbose_name='Cloth name')),
                ('image', models.ImageField(default='clothes/default.jpg', upload_to=clothes.models.user_directory_path)),
                ('preference_index', models.IntegerField(default=1, verbose_name='Preference')),
                ('max_temp', models.IntegerField(default=0, verbose_name='Maximum temperature')),
                ('min_temp', models.IntegerField(default=0, verbose_name='Minimum temperature')),
            ],
            options={
                'db_table': 'clothes_garment',
            },
        ),
    ]
