# Generated by Django 4.0 on 2022-01-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.CharField(choices=[('none', 'None'), ('sun', 'Sun'), ('rain', 'Rain'), ('wind', 'Wind'), ('snow', 'Snow')], default='none', max_length=20)),
            ],
            options={
                'db_table': 'weather_type',
            },
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathegory', models.CharField(choices=[('none', 'None'), ('t-shirt', 'T-Shirt'), ('trousers', 'Trousers'), ('hoodie', 'Hoodie'), ('jacket', 'Jacket'), ('shorts', 'Shorts'), ('shirt', 'Shirt')], default='none', max_length=20)),
                ('name', models.CharField(default='', max_length=200)),
                ('preference_index', models.IntegerField(default=1)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
                ('weather_type_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='clothes.weathertype')),
            ],
            options={
                'db_table': 'clothes_garment',
            },
        ),
    ]
