# Generated by Django 4.0 on 2022-01-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='garment',
            old_name='weather_type_id',
            new_name='weather_type',
        ),
    ]
