# Generated by Django 4.0 on 2022-01-03 21:45

import clothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_rename_user_id_garment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathertype',
            name='weather_type',
        ),
        migrations.AddField(
            model_name='garment',
            name='image',
            field=models.ImageField(default='clothes/default.jpg', upload_to=clothes.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='weathertype',
            name='cloudy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weathertype',
            name='rainy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weathertype',
            name='snowy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weathertype',
            name='sunny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weathertype',
            name='temperature',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='weathertype',
            name='windy',
            field=models.BooleanField(default=False),
        ),
    ]
