# Generated by Django 4.0 on 2022-01-04 14:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_remove_weathertype_weather_type_garment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='weather_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('none', 'None'), ('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('windy', 'Windy')], max_length=35),
        ),
    ]
